#!/bin/bash

# QPCR S-Curve Analyzer - Agent Onboarding Script
# This script ensures new agents read critical project documentation

echo "🚨 NEW AGENT DETECTED 🚨"
echo ""
echo "MANDATORY READING REQUIRED:"
echo "📖 Agent_instructions.md - Contains ALL critical project information"
echo ""
echo "KEY TOPICS COVERED:"
echo "✅ Data contamination prevention system (CRITICAL)"
echo "✅ Current project status and recent fixes"
echo "✅ Protected functions and safety mechanisms"
echo "✅ Branch management and testing procedures"
echo "✅ Pattern recognition fixes (January 2025)"
echo "✅ Threshold integrity and statistics accuracy"
echo ""
echo "BEFORE PROCEEDING:"
echo "1. Read /workspaces/QPCR-S-Curve-Analyzer/Agent_instructions.md COMPLETELY"
echo "2. Understand the emergencyReset() and contamination protection system"
echo "3. Check current branch status and recent commits"
echo "4. Test the emergency reset button functionality"
echo "5. Follow documentation policy - update Agent_instructions.md only"
echo ""
echo "⚠️  CRITICAL WARNINGS ⚠️"
echo "❌ NEVER use direct assignment to currentAnalysisResults"
echo "❌ NEVER bypass contamination protection functions"
echo "❌ NEVER create standalone documentation files"
echo "✅ ALWAYS use setAnalysisResults() for safe state management"
echo "✅ ALWAYS use displayHistorySession() for history viewing"
echo "✅ ALWAYS call emergencyReset() before loading history"
echo ""
echo "📁 Project Documentation Structure:"
echo "   - Agent_instructions.md (PRIMARY - read this first)"
echo "   - docs/ folder (archive - reference only)"
echo "   - .agent_setup.md (this reminder)"
echo ""
echo "🔄 This ensures project continuity and prevents regression"
echo ""
echo "Ready to proceed? Confirm you've read Agent_instructions.md completely."
