[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask-sqlalchemy>=3.1.1",
    "flask>=3.1.1",
    "pandas>=2.3.0",
    "sqlalchemy>=2.0.41",
    "psycopg2-binary>=2.9.10",
    "numpy>=2.3.0",
    "scipy>=1.15.3",
    "matplotlib>=3.10.3",
    "scikit-learn>=1.7.0",
    "setuptools>=80.9.0",
    "pymysql>=1.1.1",
    "mysql-connector-python>=9.3.0",
]
