[build]
builder = "nixpacks"

[deploy]
startCommand = "python app.py"
healthcheckPath = "/ping"
healthcheckTimeout = 60
healthcheckInterval = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[networking]
externalPort = 5000
internalPort = 5000

[environment]
PORT = "5000"
DATABASE_URL = ""
FLASK_ENV = "production"