[build]
builder = "nixpacks"

[deploy]
startCommand = "python app.py"
healthcheckPath = "/health"
healthcheckTimeout = 60
healthcheckInterval = 5
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[networking]
externalPort = 5000
internalPort = 5000

[environment]
PORT = "5000"
DATABASE_URL = ""
FLASK_ENV = "production"
[nixpacks]
language = "python"
pythonVersion = "3.11"
